dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.2.2
  - OpenZeppelin/openzeppelin-contracts@4.3.2
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.2'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2'
dotenv: .env
networks:
  default: development
  development:
    token: "0xfc81C286040505C4B209C8b11Fa25Bf85aF0CF00"
    sale: "0xc50eE3e8A4a694994e79e3725Ee6E0962a617b2C"
    verify: False
  ganache-local:
    verify: False
  bsc-test:
    eth_usd_price_feed: "0x2514895c72f50D8bd4B4F9b1110F0D6bD2c97526"
    verify: True
  rinkeby:
    vrf_coordinator: "0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B"
    eth_usd_price_feed:  "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    link_token: "0x01BE23585060835E02B77ef475b0Cc51aA1e0709"
    keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    fee: 100000000000000000
    verify: True
  mainnet-fork:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}